<package format="2">
  <name>za_experimental</name>
  <version>0.1.0</version>
  <description>This package contains experimental launch files and alternative configs</description>

  <license>Apache 2.0</license>

  <maintainer email="andreas.zachariae@gmail.com">Andreas Zachariae</maintainer>
  <author email="andreas.zachariae@gmail.com">Andreas Zachariae</author>

  <buildtool_depend>catkin</buildtool_depend>

  <!-- <exec_depend>cob_default_env_config</exec_depend>
  <exec_depend>cob_default_robot_config</exec_depend>
  <exec_depend>cob_gazebo_worlds</exec_depend>
  <exec_depend>cob_gazebo</exec_depend>
  <exec_depend>gazebo_ros</exec_depend> -->

  <!-- <test_depend>cob_default_env_config</test_depend>
  <test_depend>cob_supported_robots</test_depend>
  <test_depend>roslaunch</test_depend> -->

</package>
